name: Build and Run Roslyn Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 4.7.2

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Roslyn project
      run: dotnet build

    - name: Run Roslyn project
      run: dotnet run --project CodeAnalyzer/CodeAnalyzer.csproj