name: Build and Run Roslyn Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore CodeAnalyzer.csproj

    - name: Build and Run Roslyn Analysis
      run: |
        dotnet build --configuration Release

        dotnet run --project CodeAnalyzer.csproj
        
        MSBuildLocator.Unregister
